---
jobs:
- name: publish
  plan:
  - get: pcf-cloud-native
    trigger: true
  - put: cloud-foundry
    params:
      manifest: pcf-cloud-native/manifest.yml
      path: pcf-cloud-native
      current_app_name: absg-workshop
  - put: tracker
    params:
      repos:
        - pcf-cloud-native

resources:
- name: pcf-cloud-native
  type: git
  source:
    uri: https://github.com/patrickcrocker/pcf-cloud-native.git
    branch: master

- name: cloud-foundry
  type: cf
  source:
    api: api.system.anvil.pcfdemo.com
    username: {{cf-username}}
    password: {{cf-password}}
    organization: ABSG
    space: workshop

- name: tracker
  type: tracker
  source:
    token: {{tracker-api-token}}
    project_id: {{tracker-project-id}}
    tracker_url: {{tracker-url}}
